In [84]:
import pandas as pd
import numpy as np

In [55]:
df_productos = pd.read_csv('productos_portatiles_actualizado.csv')
df_productos.head()

producto_id            timestamp  \
0            1  2025-02-28 08:40:09   
1            2  2025-02-28 08:40:24   
2            3  2025-02-28 08:40:41   
3            4  2025-02-28 08:40:57   
4            5  2025-02-28 08:41:11   

                                              nombre  \
0  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

                                                 url   precio precio_tachado  \
0  https://www.pccomponentes.com/acer-travelmate-...  758,98€              0   
1  https://www.pccomponentes.com/portatil-acer-tr...  728,79€              0   
2  https://www.pccomponentes.com/acer-travelmate-...  912,04€              0   
3  https://www.pccomponentes.com/acer-travelmate-...  769,60€              0   
4  https://www.pccomponentes.com/acer-travelmate-...  842,33€              0   

  rating           opiniones  categoria_id  
0  4,7/5  7.386 valoraciones             4  
1  3,8/5    271 valoraciones             4  
2  4,7/5  7.386 valoraciones             1  
3  3,8/5    271 valoraciones             4  
4      0                   0             4

In [56]:
df_caracteristicas = pd.read_csv('caracteristicas_portatiles_actualizado.csv')
df_caracteristicas.head()

producto_id Processor Speed Processor Cores RAM Gbs Storage Gbs  \
0            1             NaN             NaN     NaN         NaN   
1            2         2.6 GHz               8      16         512   
2            3         4.70GHz              10    16GB       512GB   
3            4          3.0Ghz              16      64         512   
4            5             NaN             NaN     NaN         NaN   

  Display Inches               GPU Model USB Ports Operating System  Weight  \
0            NaN                     NaN         0              NaN     NaN   
1           15.4      NVidia RTX 4080 Ti         3              NaN     NaN   
2           15.6  Intel Iris Xe Graphics         4   Windows 11 Pro  1.90kg   
3             17      NVidia RTX 4080 Ti         2              NaN     NaN   
4            NaN                     NaN       NaN              NaN     NaN   

  Battery mAh  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

In [57]:
df_categorias = pd.read_csv('categoriasPortatiles.csv')
df_categorias.head()

id                                 nombre  \
0   1                      Portátiles gaming   
1   2             Portátiles gaming avanzado   
2   3    Portátiles para estudiar o trabajar   
3   4  Portátiles de uso básico y navegación   
4   5                Portátiles ultraligeros   

                                                 url  
0  https://www.pccomponentes.com/portatiles/amd-r...  
1  https://www.pccomponentes.com/portatiles/amd-r...  
2  https://www.pccomponentes.com/portatiles/15-6-...  
3  https://www.pccomponentes.com/portatiles/8-gb-...  
4  https://www.pccomponentes.com/portatiles/13-3-...

In [58]:
#Merge de productos y caracteristicas
df_productos_caracteristicas = pd.merge(df_productos, df_caracteristicas, on='producto_id', how= 'outer')
df_productos_caracteristicas.head()

producto_id            timestamp  \
0            1  2025-02-28 08:40:09   
1            2  2025-02-28 08:40:24   
2            3  2025-02-28 08:40:41   
3            4  2025-02-28 08:40:57   
4            5  2025-02-28 08:41:11   

                                              nombre  \
0  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

                                                 url   precio precio_tachado  \
0  https://www.pccomponentes.com/acer-travelmate-...  758,98€              0   
1  https://www.pccomponentes.com/portatil-acer-tr...  728,79€              0   
2  https://www.pccomponentes.com/acer-travelmate-...  912,04€              0   
3  https://www.pccomponentes.com/acer-travelmate-...  769,60€              0   
4  https://www.pccomponentes.com/acer-travelmate-...  842,33€              0   

  rating           opiniones  categoria_id Processor Speed Processor Cores  \
0  4,7/5  7.386 valoraciones             4             NaN             NaN   
1  3,8/5    271 valoraciones             4         2.6 GHz               8   
2  4,7/5  7.386 valoraciones             1         4.70GHz              10   
3  3,8/5    271 valoraciones             4          3.0Ghz              16   
4      0                   0             4             NaN             NaN   

  RAM Gbs Storage Gbs Display Inches               GPU Model USB Ports  \
0     NaN         NaN            NaN                     NaN         0   
1      16         512           15.4      NVidia RTX 4080 Ti         3   
2    16GB       512GB           15.6  Intel Iris Xe Graphics         4   
3      64         512             17      NVidia RTX 4080 Ti         2   
4     NaN         NaN            NaN                     NaN       NaN   

  Operating System  Weight Battery mAh  
0              NaN     NaN         NaN  
1              NaN     NaN         NaN  
2   Windows 11 Pro  1.90kg         NaN  
3              NaN     NaN         NaN  
4              NaN     NaN         NaN

In [59]:
df_merged = pd.merge(df_productos_caracteristicas, df_categorias, left_on='categoria_id', right_on='id', how= 'left')
df_merged.head()

producto_id            timestamp  \
0            1  2025-02-28 08:40:09   
1            2  2025-02-28 08:40:24   
2            3  2025-02-28 08:40:41   
3            4  2025-02-28 08:40:57   
4            5  2025-02-28 08:41:11   

                                            nombre_x  \
0  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

                                               url_x   precio precio_tachado  \
0  https://www.pccomponentes.com/acer-travelmate-...  758,98€              0   
1  https://www.pccomponentes.com/portatil-acer-tr...  728,79€              0   
2  https://www.pccomponentes.com/acer-travelmate-...  912,04€              0   
3  https://www.pccomponentes.com/acer-travelmate-...  769,60€              0   
4  https://www.pccomponentes.com/acer-travelmate-...  842,33€              0   

  rating           opiniones  categoria_id Processor Speed  ... Storage Gbs  \
0  4,7/5  7.386 valoraciones             4             NaN  ...         NaN   
1  3,8/5    271 valoraciones             4         2.6 GHz  ...         512   
2  4,7/5  7.386 valoraciones             1         4.70GHz  ...       512GB   
3  3,8/5    271 valoraciones             4          3.0Ghz  ...         512   
4      0                   0             4             NaN  ...         NaN   

  Display Inches               GPU Model USB Ports Operating System  Weight  \
0            NaN                     NaN         0              NaN     NaN   
1           15.4      NVidia RTX 4080 Ti         3              NaN     NaN   
2           15.6  Intel Iris Xe Graphics         4   Windows 11 Pro  1.90kg   
3             17      NVidia RTX 4080 Ti         2              NaN     NaN   
4            NaN                     NaN       NaN              NaN     NaN   

  Battery mAh id                               nombre_y  \
0         NaN  4  Portátiles de uso básico y navegación   
1         NaN  4  Portátiles de uso básico y navegación   
2         NaN  1                      Portátiles gaming   
3         NaN  4  Portátiles de uso básico y navegación   
4         NaN  4  Portátiles de uso básico y navegación   

                                               url_y  
0  https://www.pccomponentes.com/portatiles/8-gb-...  
1  https://www.pccomponentes.com/portatiles/8-gb-...  
2  https://www.pccomponentes.com/portatiles/amd-r...  
3  https://www.pccomponentes.com/portatiles/8-gb-...  
4  https://www.pccomponentes.com/portatiles/8-gb-...  

[5 rows x 22 columns]

In [60]:
df_merged.drop(columns=['id','url_x','url_y','producto_id','categoria_id'], inplace=True)

In [61]:
df_merged.head()


timestamp                                           nombre_x  \
0  2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

    precio precio_tachado rating           opiniones Processor Speed  \
0  758,98€              0  4,7/5  7.386 valoraciones             NaN   
1  728,79€              0  3,8/5    271 valoraciones         2.6 GHz   
2  912,04€              0  4,7/5  7.386 valoraciones         4.70GHz   
3  769,60€              0  3,8/5    271 valoraciones          3.0Ghz   
4  842,33€              0      0                   0             NaN   

  Processor Cores RAM Gbs Storage Gbs Display Inches               GPU Model  \
0             NaN     NaN         NaN            NaN                     NaN   
1               8      16         512           15.4      NVidia RTX 4080 Ti   
2              10    16GB       512GB           15.6  Intel Iris Xe Graphics   
3              16      64         512             17      NVidia RTX 4080 Ti   
4             NaN     NaN         NaN            NaN                     NaN   

  USB Ports Operating System  Weight Battery mAh  \
0         0              NaN     NaN         NaN   
1         3              NaN     NaN         NaN   
2         4   Windows 11 Pro  1.90kg         NaN   
3         2              NaN     NaN         NaN   
4       NaN              NaN     NaN         NaN   

                                nombre_y  
0  Portátiles de uso básico y navegación  
1  Portátiles de uso básico y navegación  
2                      Portátiles gaming  
3  Portátiles de uso básico y navegación  
4  Portátiles de uso básico y navegación

In [62]:
df_merged.rename(columns={'nombre_y': 'categoria'}, inplace=True)
df_merged.head()

timestamp                                           nombre_x  \
0  2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

    precio precio_tachado rating           opiniones Processor Speed  \
0  758,98€              0  4,7/5  7.386 valoraciones             NaN   
1  728,79€              0  3,8/5    271 valoraciones         2.6 GHz   
2  912,04€              0  4,7/5  7.386 valoraciones         4.70GHz   
3  769,60€              0  3,8/5    271 valoraciones          3.0Ghz   
4  842,33€              0      0                   0             NaN   

  Processor Cores RAM Gbs Storage Gbs Display Inches               GPU Model  \
0             NaN     NaN         NaN            NaN                     NaN   
1               8      16         512           15.4      NVidia RTX 4080 Ti   
2              10    16GB       512GB           15.6  Intel Iris Xe Graphics   
3              16      64         512             17      NVidia RTX 4080 Ti   
4             NaN     NaN         NaN            NaN                     NaN   

  USB Ports Operating System  Weight Battery mAh  \
0         0              NaN     NaN         NaN   
1         3              NaN     NaN         NaN   
2         4   Windows 11 Pro  1.90kg         NaN   
3         2              NaN     NaN         NaN   
4       NaN              NaN     NaN         NaN   

                               categoria  
0  Portátiles de uso básico y navegación  
1  Portátiles de uso básico y navegación  
2                      Portátiles gaming  
3  Portátiles de uso básico y navegación  
4  Portátiles de uso básico y navegación

In [63]:
df_merged.info()   

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1152 entries, 0 to 1151
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   timestamp         1152 non-null   object
 1   nombre_x          1152 non-null   object
 2   precio            1152 non-null   object
 3   precio_tachado    1152 non-null   object
 4   rating            1152 non-null   object
 5   opiniones         1152 non-null   object
 6   Processor Speed   623 non-null    object
 7   Processor Cores   814 non-null    object
 8   RAM Gbs           802 non-null    object
 9   Storage Gbs       794 non-null    object
 10  Display Inches    794 non-null    object
 11  GPU Model         703 non-null    object
 12  USB Ports         826 non-null    object
 13  Operating System  596 non-null    object
 14  Weight            627 non-null    object
 15  Battery mAh       134 non-null    object
 16  categoria         1152 non-null   object
dtypes: object(17)


In [64]:
df_merged['opiniones'] = df_merged['opiniones'].str.replace(r'\D', '', regex=True)
df_merged['opiniones'] = df_merged['opiniones'].fillna(0)
df_merged['opiniones'] = df_merged['opiniones'].astype(int)
df_merged.head()

timestamp                                           nombre_x  \
0  2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

    precio precio_tachado rating  opiniones Processor Speed Processor Cores  \
0  758,98€              0  4,7/5       7386             NaN             NaN   
1  728,79€              0  3,8/5        271         2.6 GHz               8   
2  912,04€              0  4,7/5       7386         4.70GHz              10   
3  769,60€              0  3,8/5        271          3.0Ghz              16   
4  842,33€              0      0          0             NaN             NaN   

  RAM Gbs Storage Gbs Display Inches               GPU Model USB Ports  \
0     NaN         NaN            NaN                     NaN         0   
1      16         512           15.4      NVidia RTX 4080 Ti         3   
2    16GB       512GB           15.6  Intel Iris Xe Graphics         4   
3      64         512             17      NVidia RTX 4080 Ti         2   
4     NaN         NaN            NaN                     NaN       NaN   

  Operating System  Weight Battery mAh                              categoria  
0              NaN     NaN         NaN  Portátiles de uso básico y navegación  
1              NaN     NaN         NaN  Portátiles de uso básico y navegación  
2   Windows 11 Pro  1.90kg         NaN                      Portátiles gaming  
3              NaN     NaN         NaN  Portátiles de uso básico y navegación  
4              NaN     NaN         NaN  Portátiles de uso básico y navegación

In [65]:
df_merged['rating'] = df_merged['rating'].str.replace(',', '.', regex=False)
df_merged['rating'] = df_merged['rating'].str.replace(r'/5', '', regex=True)
df_merged['rating'] = df_merged['rating'].astype(float)
df_merged.head()

timestamp                                           nombre_x  \
0  2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

    precio precio_tachado  rating  opiniones Processor Speed Processor Cores  \
0  758,98€              0     4.7       7386             NaN             NaN   
1  728,79€              0     3.8        271         2.6 GHz               8   
2  912,04€              0     4.7       7386         4.70GHz              10   
3  769,60€              0     3.8        271          3.0Ghz              16   
4  842,33€              0     0.0          0             NaN             NaN   

  RAM Gbs Storage Gbs Display Inches               GPU Model USB Ports  \
0     NaN         NaN            NaN                     NaN         0   
1      16         512           15.4      NVidia RTX 4080 Ti         3   
2    16GB       512GB           15.6  Intel Iris Xe Graphics         4   
3      64         512             17      NVidia RTX 4080 Ti         2   
4     NaN         NaN            NaN                     NaN       NaN   

  Operating System  Weight Battery mAh                              categoria  
0              NaN     NaN         NaN  Portátiles de uso básico y navegación  
1              NaN     NaN         NaN  Portátiles de uso básico y navegación  
2   Windows 11 Pro  1.90kg         NaN                      Portátiles gaming  
3              NaN     NaN         NaN  Portátiles de uso básico y navegación  
4              NaN     NaN         NaN  Portátiles de uso básico y navegación

In [66]:
df_merged['precio'] = df_merged['precio'].str.replace('.', '', regex=False)
df_merged['precio'] = df_merged['precio'].str.replace(',', '.', regex=False)
df_merged['precio'] = df_merged['precio'].str.replace(r'€', '', regex=True)
df_merged['precio'] = df_merged['precio'].astype(float)
df_merged.head()

timestamp                                           nombre_x  \
0  2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

   precio precio_tachado  rating  opiniones Processor Speed Processor Cores  \
0  758.98              0     4.7       7386             NaN             NaN   
1  728.79              0     3.8        271         2.6 GHz               8   
2  912.04              0     4.7       7386         4.70GHz              10   
3  769.60              0     3.8        271          3.0Ghz              16   
4  842.33              0     0.0          0             NaN             NaN   

  RAM Gbs Storage Gbs Display Inches               GPU Model USB Ports  \
0     NaN         NaN            NaN                     NaN         0   
1      16         512           15.4      NVidia RTX 4080 Ti         3   
2    16GB       512GB           15.6  Intel Iris Xe Graphics         4   
3      64         512             17      NVidia RTX 4080 Ti         2   
4     NaN         NaN            NaN                     NaN       NaN   

  Operating System  Weight Battery mAh                              categoria  
0              NaN     NaN         NaN  Portátiles de uso básico y navegación  
1              NaN     NaN         NaN  Portátiles de uso básico y navegación  
2   Windows 11 Pro  1.90kg         NaN                      Portátiles gaming  
3              NaN     NaN         NaN  Portátiles de uso básico y navegación  
4              NaN     NaN         NaN  Portátiles de uso básico y navegación

In [67]:
df_merged['precio_tachado'] = df_merged['precio_tachado'].str.replace('.', '', regex=False)
df_merged['precio_tachado'] = df_merged['precio_tachado'].str.replace(',', '.', regex=False)
df_merged['precio_tachado'] = df_merged['precio_tachado'].str.replace(r'€', '', regex=True)
# df_merged['precio_tachado'] = df_merged['precio_tachado'].fillna(df['precio'])
df_merged['precio_tachado'] = df_merged['precio_tachado'].astype(float)
df_merged.head()

timestamp                                           nombre_x  \
0  2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1  2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2  2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3  2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4  2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

   precio  precio_tachado  rating  opiniones Processor Speed Processor Cores  \
0  758.98             0.0     4.7       7386             NaN             NaN   
1  728.79             0.0     3.8        271         2.6 GHz               8   
2  912.04             0.0     4.7       7386         4.70GHz              10   
3  769.60             0.0     3.8        271          3.0Ghz              16   
4  842.33             0.0     0.0          0             NaN             NaN   

  RAM Gbs Storage Gbs Display Inches               GPU Model USB Ports  \
0     NaN         NaN            NaN                     NaN         0   
1      16         512           15.4      NVidia RTX 4080 Ti         3   
2    16GB       512GB           15.6  Intel Iris Xe Graphics         4   
3      64         512             17      NVidia RTX 4080 Ti         2   
4     NaN         NaN            NaN                     NaN       NaN   

  Operating System  Weight Battery mAh                              categoria  
0              NaN     NaN         NaN  Portátiles de uso básico y navegación  
1              NaN     NaN         NaN  Portátiles de uso básico y navegación  
2   Windows 11 Pro  1.90kg         NaN                      Portátiles gaming  
3              NaN     NaN         NaN  Portátiles de uso básico y navegación  
4              NaN     NaN         NaN  Portátiles de uso básico y navegación

In [68]:
df_merged['timestamp'] = pd.to_datetime(df_merged['timestamp'])

In [69]:
df_merged['Processor Speed'] = df_merged['Processor Speed'].str.extract(r'([\d.]+)')
df_merged['Processor Speed'] = df_merged['Processor Speed'].astype(float)
df_merged.head()

timestamp                                           nombre_x  \
0 2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1 2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2 2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3 2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4 2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

   precio  precio_tachado  rating  opiniones  Processor Speed Processor Cores  \
0  758.98             0.0     4.7       7386              NaN             NaN   
1  728.79             0.0     3.8        271              2.6               8   
2  912.04             0.0     4.7       7386              4.7              10   
3  769.60             0.0     3.8        271              3.0              16   
4  842.33             0.0     0.0          0              NaN             NaN   

  RAM Gbs Storage Gbs Display Inches               GPU Model USB Ports  \
0     NaN         NaN            NaN                     NaN         0   
1      16         512           15.4      NVidia RTX 4080 Ti         3   
2    16GB       512GB           15.6  Intel Iris Xe Graphics         4   
3      64         512             17      NVidia RTX 4080 Ti         2   
4     NaN         NaN            NaN                     NaN       NaN   

  Operating System  Weight Battery mAh                              categoria  
0              NaN     NaN         NaN  Portátiles de uso básico y navegación  
1              NaN     NaN         NaN  Portátiles de uso básico y navegación  
2   Windows 11 Pro  1.90kg         NaN                      Portátiles gaming  
3              NaN     NaN         NaN  Portátiles de uso básico y navegación  
4              NaN     NaN         NaN  Portátiles de uso básico y navegación

In [78]:
df_merged['Processor Cores'] = df_merged['Processor Cores'].astype(str)
df_merged['Processor Cores'] = df_merged['Processor Cores'].str.extract(r'(\d+)')
df_merged['Processor Cores'] = pd.to_numeric(df_merged['Processor Cores'], errors='coerce')
df_merged['Processor Cores'].astype(float)
df_merged['Processor Cores'].unique()

array([ nan,   8.,  10.,  16.,   0.,   6.,   4.,   1.,   2.,  14.,  12.,
        20.,  24., 128.])

In [82]:
df_merged['RAM Gbs'].unique()
df_merged['RAM Gbs'] = df_merged['RAM Gbs'].str.extract(r'(\d+)')
df_merged['RAM Gbs'] = pd.to_numeric(df_merged['RAM Gbs'], errors='coerce')
df_merged['RAM Gbs'].unique()

array([nan, 16., 64.,  8., 32.,  0., 48., 12., 83.,  4., 24.])

In [76]:
df_merged['Storage Gbs'] = df_merged['Storage Gbs'].astype(str)
df_merged['Storage Gbs'] = df_merged['Storage Gbs'].str.replace(r'(\d+)\s*TB', lambda x: str(int(x.group(1)) * 1000), regex=True)
df_merged['Storage Gbs'] = df_merged['Storage Gbs'].astype(str)
df_merged['Storage Gbs'] = df_merged['Storage Gbs'].str.extract(r'(\d+)')
df_merged['Storage Gbs'] = pd.to_numeric(df_merged['Storage Gbs'], errors='coerce')
df_merged['Storage Gbs'].astype(float)
df_merged.head()

timestamp                                           nombre_x  \
0 2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1 2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2 2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3 2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4 2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

   precio  precio_tachado  rating  opiniones  Processor Speed  \
0  758.98             0.0     4.7       7386              NaN   
1  728.79             0.0     3.8        271              2.6   
2  912.04             0.0     4.7       7386              4.7   
3  769.60             0.0     3.8        271              3.0   
4  842.33             0.0     0.0          0              NaN   

   Processor Cores RAM Gbs  Storage Gbs Display Inches  \
0              NaN     NaN          NaN            NaN   
1              8.0      16        512.0           15.4   
2             10.0    16GB        512.0           15.6   
3             16.0      64        512.0             17   
4              NaN     NaN          NaN            NaN   

                GPU Model USB Ports Operating System  Weight Battery mAh  \
0                     NaN         0              NaN     NaN         NaN   
1      NVidia RTX 4080 Ti         3              NaN     NaN         NaN   
2  Intel Iris Xe Graphics         4   Windows 11 Pro  1.90kg         NaN   
3      NVidia RTX 4080 Ti         2              NaN     NaN         NaN   
4                     NaN       NaN              NaN     NaN         NaN   

                               categoria  
0  Portátiles de uso básico y navegación  
1  Portátiles de uso básico y navegación  
2                      Portátiles gaming  
3  Portátiles de uso básico y navegación  
4  Portátiles de uso básico y navegación

In [79]:
df_merged['Storage Gbs'].unique()

array([      nan, 5.120e+02, 1.000e+00, 1.000e+03, 1.024e+03, 2.560e+02,
       5.000e+02, 0.000e+00, 8.000e+03, 2.048e+03, 2.000e+03, 8.300e+01,
       3.200e+01, 1.280e+02, 8.000e+00, 6.400e+01])

In [80]:
df_merged['Display Inches'] = df_merged['Display Inches'].astype(str)  
df_merged['Display Inches'] = df_merged['Display Inches'].str.extract(r'([\d.]+)')
df_merged['Display Inches'] = pd.to_numeric(df_merged['Display Inches'], errors='coerce')
df_merged['Display Inches'].unique()

array([   nan,  15.4 ,  15.6 ,  17.  ,  14.  ,  13.3 ,  13.  ,  13.6 ,
        15.3 ,  12.9 ,  16.  ,  14.2 ,  17.3 ,   0.  ,  15.5 ,  35.98,
        13.5 ,  14.1 ,  16.1 ,  15.65,  35.65,  15.  ,  15.7 ,  11.6 ,
        13.4 ,  14.9 ,  13.9 ,  15.63,  12.5 ,  14.5 ,  13.8 ,  13.7 ,
        12.3 ,  10.1 ,  13.27,  13.94,  12.28, 359.7 ,  14.98])

In [88]:
gpu_brands = ['NVidia', 'Intel', 'AMD', 'Apple']

def extract_brand(gpu_name):
    for brand in gpu_brands:
        if brand.lower() in str(gpu_name).lower(): 
            return brand
    return np.nan  

df_merged['GPU Model'] = df_merged['GPU Model'].apply(extract_brand)
df_merged['GPU Model'].unique()

array([nan, 'NVidia', 'Intel', 'AMD', 'Apple'], dtype=object)

In [87]:
df_merged.head()

timestamp                                           nombre_x  \
0 2025-02-28 08:40:09  Acer TravelMate P2 TMP214-55-TCO-51RL Intel Co...   
1 2025-02-28 08:40:24  Portátil Acer TravelMate P2 TMP215-54-584F Int...   
2 2025-02-28 08:40:41  Acer TravelMate P2 TMP215-54-71UZ Intel Core i...   
3 2025-02-28 08:40:57  Acer TravelMate P2 TMP216-51-TCO-346K Netbook ...   
4 2025-02-28 08:41:11  Acer TravelMate P2 TMP216-51-TCO-5584 Intel Co...   

   precio  precio_tachado  rating  opiniones  Processor Speed  \
0  758.98             0.0     4.7       7386              NaN   
1  728.79             0.0     3.8        271              2.6   
2  912.04             0.0     4.7       7386              4.7   
3  769.60             0.0     3.8        271              3.0   
4  842.33             0.0     0.0          0              NaN   

   Processor Cores  RAM Gbs  Storage Gbs  Display Inches GPU Model USB Ports  \
0              NaN      NaN          NaN             NaN       NaN         0   
1              8.0     16.0        512.0            15.4    NVidia         3   
2             10.0     16.0        512.0            15.6     Intel         4   
3             16.0     64.0        512.0            17.0    NVidia         2   
4              NaN      NaN          NaN             NaN       NaN       NaN   

  Operating System  Weight Battery mAh                              categoria  
0              NaN     NaN         NaN  Portátiles de uso básico y navegación  
1              NaN     NaN         NaN  Portátiles de uso básico y navegación  
2   Windows 11 Pro  1.90kg         NaN                      Portátiles gaming  
3              NaN     NaN         NaN  Portátiles de uso básico y navegación  
4              NaN     NaN         NaN  Portátiles de uso básico y navegación

In [90]:
df_merged['USB Ports'] = df_merged['USB Ports'].astype(str).str.extract(r'(\d+)')
df_merged['USB Ports'] = pd.to_numeric(df_merged['USB Ports'], errors='coerce')
df_merged['USB Ports'].unique()

array([ 0.,  3.,  4.,  2., nan,  5.,  1., 11.,  7.,  6.,  8., 13.])

In [92]:
df_merged["Operating System"].unique()

array([nan, 'Windows 11 Pro', 'Windows 10 Pro', 'Windows 11', 'Windows',
       'Windows 11 Home Advanced', 'Sin sistema operativo',
       'macOS Big Sur', 'macOS', 'MacOS', 'Apple', 'Windows 10',
       'macOS Mojave', 'macOS Monterey', 'macOS, Windows 10',
       'macOS Sierra', 'macOS Catalina', 'Windows 10 Home',
       'Windows 10 Home 64 Bits', 'Windows 11 Home 64 bits',
       'Windows 11 Home', 'Windows 10 Pro 64 bits', 'u003e',
       'SIN SISTEMA OPERATIVO', 'FreeDOS (no sistema operativo)',
       'Not specified', 'FreeDOS', 'Windows 11 Home in S mode',
       'Windows 11 Home in mode S', 'Windows 11 Home 64 Bits',
       'Windows 10 Home 64 bits', 'Windows 10 home 64 bits', 'ChromeOS',
       'Windows 11 Pro 64 bits', 'Microsoft Windows 10 Pro 64bits',
       'FreeDOS (SIN SISTEMA OPERATIVO)', 'FreeDos', 'FreeDOS 3.0', 'e',
       'FreeDOS (Sin Sistema Operativo)', 'Windows 11 Pro 64 Bits',
       'Windows 10 Home in S mode', 'macOS Sonoma', 'M3 de Apple',
       'Windows 